First stage of updating to gnuradio 3.7.  Following guide published at http://gnuradio.org/redmine/projects/gnuradio/wiki/Move_3-6_to_3-7
Have accomplished the following:
 - Remove FindGnuradioCore.cmake and FindGruel.cmake, replaced with FindGnuradioRuntime.cmake
   that I pulled out of gr-utils/python/modtool/gr-newmod/cmake/Modules/FindGnuradioRuntime.cmake
 - Remove all GRUEL_ references and replace GNURADIO_CORE variables with GNURADIO_RUNTIME_
 - Update #include<gruel/attributes.h> to <gnuradio/attributes.h>
 - Changed file structure:
   - from gr-specest/include/specest-blockname.h to gr-specest/include/specest/blockname.h
   - from gr-specest/lib/specest-blockname.cc to gr-specest/lib/blockname.cc
     (actually, I think that there was some significant changes that should have been done to split
     blockname.cc into blockname_impl.h and blockname_impl.cc but I'm actually confused by all the
     blockname_impl.h that are placed under include/specest, and I'm not entirely sure that the
     split didn't already happen under 3.6)
 - Updated gnuradio header files e.g. '#include <gr_sync_block.h>' to '#include <gnuradio/sync_block.h'
 - Updated gnuradio classes and functions to new namespace, e.g. gr_make_io_signature() to gr::io_signature::make()

Current status:
 - Complilation errors caused by the need for above updates now worked out and the files compile without error.
 - Build currently broken, stuck at linker errors:
     ....
     [ 52%] Built target gnuradio-specest
     Linking CXX executable qa_arburg_impl
     libgnuradio-specest.so: undefined reference to `fftwf_free'
     libgnuradio-specest.so: undefined reference to `fftwf_malloc'
     ....
 - Will be looking into the FindGnuradioRuntime.cmake file I lifted from gr-utils
 - Would love suggestions on how to debug this, "nm" and "ldd" show issues but not root causes...

Work not yet started:
 - updating the gr-specest namespace to the new format
 - adding new blocks:  cross-correlation, normalization, running sum, etc